import { PaletteItem } from '../components/NodeEditor/types';

export const MODELS: PaletteItem[] = [
    { name: 'Nano Banana', type: 'stableDiffusion', icon: '🍌', symbol: 'NB', category: 'Image Gen', brand: 'Google', slug: 'google/nano-banana' },
    { name: 'Nano Banana Pro', type: 'stableDiffusion', icon: '🍌', symbol: 'NBP', category: 'Image Gen', brand: 'Google', slug: 'google/nano-banana-pro' },
    { name: 'Imagen 4', type: 'stableDiffusion', icon: '🅶', symbol: 'IM4', category: 'Image Gen', brand: 'Google', slug: 'google/imagen-4' },
    { name: 'Imagen 4 Fast', type: 'stableDiffusion', icon: '🅶', symbol: 'IM4F', category: 'Image Gen', brand: 'Google', slug: 'google/imagen-4-fast' },
    { name: 'Imagen 4 Ultra', type: 'stableDiffusion', icon: '🅶', symbol: 'IM4U', category: 'Image Gen', brand: 'Google', slug: 'google/imagen-4-ultra' },
    { name: 'Imagen 3', type: 'stableDiffusion', icon: '🅶', symbol: 'G', category: 'Image Gen', brand: 'Google', slug: 'google/imagen-3', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Imagen 3 Fast', type: 'stableDiffusion', icon: '🅶', symbol: 'G', category: 'Image Gen', brand: 'Google', slug: 'google/imagen-3-fast', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'GPT-5 Nano', type: 'stableDiffusion', icon: '🧠', symbol: 'GPT5', category: 'Image Gen', brand: 'OpenAI', slug: 'openai/gpt-5-nano', logo: 'https://logo.clearbit.com/openai.com' },
    { name: 'GPT-4.1 Nano', type: 'stableDiffusion', icon: '🧠', symbol: 'GPT4', category: 'Image Gen', brand: 'OpenAI', slug: 'openai/gpt-4.1-nano', logo: 'https://logo.clearbit.com/openai.com' },
    { name: 'Gemini 2.5 Flash Image', type: 'stableDiffusion', icon: '🅶', symbol: 'G', category: 'Image Gen', brand: 'Google', slug: 'google/gemini-2.5-flash-image', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Flux Pro 1.1 Ultra', type: 'stableDiffusion', icon: '⚡', symbol: 'FX', category: 'Image Gen', brand: 'Black Forest Labs', slug: 'black-forest-labs/flux-1.1-pro-ultra', logo: 'https://logo.clearbit.com/blackforestlabs.ai' },
    { name: 'Flux Pro 1.1', type: 'stableDiffusion', icon: '⚡', symbol: 'FX', category: 'Image Gen', brand: 'Black Forest Labs', slug: 'black-forest-labs/flux-1.1-pro', logo: 'https://logo.clearbit.com/blackforestlabs.ai' },
    { name: 'Flux Dev Redux', type: 'stableDiffusion', icon: '⚡', symbol: 'FX', category: 'Image Gen', brand: 'Black Forest Labs', slug: 'black-forest-labs/flux-dev', logo: 'https://logo.clearbit.com/blackforestlabs.ai' },
    { name: 'Flux Canny Pro', type: 'stableDiffusion', icon: '⚡', symbol: 'FX', category: 'Image Gen', brand: 'Black Forest Labs', slug: 'black-forest-labs/flux-canny-pro', logo: 'https://logo.clearbit.com/blackforestlabs.ai' },
    { name: 'Flux Depth Pro', type: 'stableDiffusion', icon: '⚡', symbol: 'FX', category: 'Image Gen', brand: 'Black Forest Labs', slug: 'black-forest-labs/flux-depth-pro', logo: 'https://logo.clearbit.com/blackforestlabs.ai' },
    { name: 'GPT Image 1', type: 'stableDiffusion', icon: '🧠', symbol: 'GPT', category: 'Image Gen', brand: 'OpenAI', slug: 'openai/dall-e-3', logo: 'https://logo.clearbit.com/openai.com' },
    { name: 'Stable Diffusion 3.5', type: 'stableDiffusion', icon: '🎨', symbol: 'SD', category: 'Image Gen', brand: 'Stability', slug: 'stability-ai/stable-diffusion-3.5-large', logo: 'https://avatars.githubusercontent.com/u/100950301?s=200&v=4' },
    { name: 'DALL·E 3', type: 'stableDiffusion', icon: '🎨', symbol: 'DAL', category: 'Image Gen', brand: 'OpenAI', slug: 'openai/dall-e-3', logo: 'https://logo.clearbit.com/openai.com' },
    { name: 'Ideogram V3', type: 'stableDiffusion', icon: '📝', symbol: 'ID3', category: 'Image Gen', brand: 'Ideogram', slug: 'ideogram-ai/ideogram-v2', logo: 'https://logo.clearbit.com/ideogram.ai' },
    { name: 'Ideogram V2', type: 'stableDiffusion', icon: '📝', symbol: 'ID2', category: 'Image Gen', brand: 'Ideogram', slug: 'ideogram-ai/ideogram-v2', logo: 'https://logo.clearbit.com/ideogram.ai' },
    { name: 'Minimax Image', type: 'stableDiffusion', icon: '🎵', symbol: 'MX', category: 'Image Gen', brand: 'Minimax', slug: 'minimax/image-01' },
    { name: 'Bria', type: 'stableDiffusion', icon: '🎪', symbol: 'BR', category: 'Image Gen', brand: 'Bria', slug: 'bria-ai/bria-2.3', logo: 'https://logo.clearbit.com/bria.ai' },
    { name: 'Runway Gen-3', type: 'stableDiffusion', icon: '🎬', symbol: 'RW', category: 'Video Gen', brand: 'Runway', slug: 'runwayml/runway-gen-3', logo: 'https://logo.clearbit.com/runwayml.com' },
    { name: 'Luma Reframe', type: 'stableDiffusion', icon: '🎞️', symbol: 'LU', category: 'Video Gen', brand: 'Luma', slug: 'luma/ray', logo: 'https://logo.clearbit.com/luma.ai' },
    { name: 'Luma Modify', type: 'stableDiffusion', icon: '🎞️', symbol: 'LU', category: 'Video Gen', brand: 'Luma', slug: 'luma/ray', logo: 'https://logo.clearbit.com/luma.ai' },
    { name: 'Veo 3', type: 'stableDiffusion', icon: '🎬', symbol: 'VEO', category: 'Video Gen', brand: 'Google', slug: 'google/veo-3', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Veo 3 Fast', type: 'stableDiffusion', icon: '🎬', symbol: 'VEO', category: 'Video Gen', brand: 'Google', slug: 'google/veo-3-fast', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Veo 3.1', type: 'stableDiffusion', icon: '🎬', symbol: 'VEO', category: 'Video Gen', brand: 'Google', slug: 'google/veo-3.1', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Veo 3.1 Fast', type: 'stableDiffusion', icon: '🎬', symbol: 'VEO', category: 'Video Gen', brand: 'Google', slug: 'google/veo-3.1-fast', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Veo 2', type: 'stableDiffusion', icon: '🎬', symbol: 'VEO', category: 'Video Gen', brand: 'Google', slug: 'google/veo-2', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Veo Text to Video', type: 'stableDiffusion', icon: '📝', symbol: 'VEO', category: 'Video Gen', brand: 'Google', slug: 'google/veo', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Veo Image to Video', type: 'stableDiffusion', icon: '🖼️', symbol: 'VEO', category: 'Video Gen', brand: 'Google', slug: 'google/veo', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Sora 2', type: 'stableDiffusion', icon: '🎥', symbol: 'SR', category: 'Video Gen', brand: 'OpenAI', slug: 'openai/sora-2', logo: 'https://logo.clearbit.com/openai.com' },
    { name: 'Hunyuan Video to Video', type: 'stableDiffusion', icon: '🎥', symbol: 'HY', category: 'Video Gen', brand: 'Hunyuan', slug: 'tencent/hunyuan-video', logo: 'https://logo.clearbit.com/tencent.com' },
    { name: 'Kling v1.6 Pro', type: 'stableDiffusion', icon: '🎥', symbol: 'KLV', category: 'Video Gen', brand: 'Kling', slug: 'kwaivgi/kling-v1.6-pro', logo: 'https://logo.clearbit.com/klingai.com' },
    { name: 'Wan 2.5', type: 'stableDiffusion', icon: '🔷', symbol: 'WN', category: 'Video Gen', brand: 'Wan', slug: 'wan-video/wan-2.5' },
    { name: 'Wan 2.2', type: 'stableDiffusion', icon: '🔷', symbol: 'WN', category: 'Video Gen', brand: 'Wan', slug: 'wan-video/wan-2.2' },
    { name: 'Wan 2.1', type: 'stableDiffusion', icon: '🔷', symbol: 'WN', category: 'Video Gen', brand: 'Wan', slug: 'wan-video/wan-2.1-t2v-14b' },
    { name: 'Omnihuman V1.5', type: 'image', icon: '👥', symbol: 'OMN', category: 'Video Gen', brand: 'Omnihuman', slug: 'tencent/omnihuman-v1.5', logo: 'https://logo.clearbit.com/tencent.com' },
    { name: 'Sync 2 Pro', type: 'image', icon: '🎤', symbol: 'SYN', category: 'Video Gen', brand: 'Sync', slug: 'sync/sync-2-pro' },
    { name: 'Pixverse Lipsync', type: 'image', icon: '👄', symbol: 'PIX', category: 'Video Gen', brand: 'Pixverse', slug: 'pixverse/lipsync', logo: 'https://logo.clearbit.com/pixverse.ai' },
    { name: 'Lyria 2', type: 'stableDiffusion', icon: '🎵', symbol: 'LY', category: 'Audio Gen', brand: 'Google', slug: 'google/lyria-2', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Video to Audio', type: 'image', icon: '🎵', symbol: 'V2A', category: 'Audio Gen', brand: 'AI', slug: 'meta/musicgen' },
    { name: 'Audio to Video', type: 'image', icon: '🎤', symbol: 'A→V', category: 'Audio Gen', brand: 'AI', slug: 'google/veo' },
    { name: 'Rodin', type: 'stableDiffusion', icon: '🎭', symbol: 'ROD', category: '3D', brand: 'Rodin', slug: 'rodin/rodin-v1' },
    { name: 'Hunyuan 3D', type: 'stableDiffusion', icon: '🎪', symbol: 'HY3', category: '3D', brand: 'Hunyuan', slug: 'tencent/hunyuan-3d-1', logo: 'https://logo.clearbit.com/tencent.com' },
    { name: 'Trellis', type: 'stableDiffusion', icon: '📦', symbol: 'TRL', category: '3D', brand: 'Trellis', slug: 'microsoft/trellis', logo: 'https://logo.clearbit.com/trellis.xyz' },
    { name: 'Meshy', type: 'stableDiffusion', icon: '🧩', symbol: 'MSH', category: '3D', brand: 'Meshy', slug: 'meshy/meshy-3', logo: 'https://logo.clearbit.com/meshy.ai' },
    { name: 'Text Box', type: 'text', icon: '✍️', symbol: 'TXT', category: 'Helpers', brand: 'AI' },
    { name: 'Copilot', type: 'text', icon: '🧠', symbol: 'AI', category: 'Helpers', brand: 'AI' },
    { name: 'Prompt Enhancer', type: 'prompt', icon: '✨', symbol: 'PE', category: 'Helpers', brand: 'AI' },
    { name: 'File Loader', type: 'imageUpload', icon: '📂', symbol: 'FILE', category: 'Helpers', brand: 'AI' },
    { name: 'Sticky Note', type: 'text', icon: '🗒️', symbol: 'NOTE', category: 'Helpers', brand: 'AI' },
    { name: 'Color Palette', type: 'text', icon: '🎨', symbol: 'COL', category: 'Helpers', brand: 'AI' },
];

export const TOOLS: PaletteItem[] = [
    { name: 'Real-ESRGAN Upscale', type: 'upscale', icon: '🔍', symbol: '↑↑', category: 'Edit', brand: 'Real-ESRGAN', slug: 'nightmareai/real-esrgan' },
    { name: 'Nano Banana Inpaint', type: 'inpaint', icon: '🍌', symbol: 'NB', category: 'Edit', brand: 'Google', slug: 'google/nano-banana-inpaint' },
    { name: 'Crop', type: 'image', icon: '✂️', symbol: 'CROP', category: 'Edit', brand: 'AI' },
    { name: 'Blur', type: 'image', icon: '💨', symbol: 'BLUR', category: 'Edit', brand: 'AI' },
    { name: 'Invert', type: 'image', icon: '🔄', symbol: 'INV', category: 'Edit', brand: 'AI' },
    { name: 'Google Relight', type: 'image', icon: '💡', symbol: 'LITE', category: 'Edit', brand: 'Google', slug: 'google/relight-2' },
    { name: 'Google Video Smoother', type: 'image', icon: '✨', symbol: 'SMOOTH', category: 'Video', brand: 'Google', slug: 'google/video-smoother' },
    { name: 'Google Frame Interpolation', type: 'image', icon: '⚡', symbol: 'FPS', category: 'Video', brand: 'Google', slug: 'google/frame-interpolation' },
    { name: 'Meta MusicGen', type: 'image', icon: '🎵', symbol: 'V→A', category: 'Video', brand: 'Meta', slug: 'meta/musicgen' },
    { name: 'Google Veo Audio2Video', type: 'image', icon: '🎤', symbol: 'A→V', category: 'Video', brand: 'Google', slug: 'google/veo' },
    { name: 'ControlNet SDXL', type: 'image', icon: '⚙️', symbol: 'CTL', category: 'Control', brand: 'HuggingFace', slug: 'huggingface/controlnet' },
    { name: 'Flux ID Preservation', type: 'image', icon: '👤', symbol: 'ID', category: 'Control', brand: 'Black Forest Labs', slug: 'black-forest-labs/flux-1.1-pro', logo: 'https://logo.clearbit.com/blackforestlabs.ai' },
    { name: 'LoRA Adapter', type: 'image', icon: '🎛️', symbol: 'LORA', category: 'Control', brand: 'AI' },
    { name: 'Vectorizer.AI', type: 'image', icon: '📐', symbol: 'VEC', category: 'Graphics', brand: 'Vectorizer', slug: 'vectorizer/vectorizer' },
    { name: 'Recraft V3 SVG', type: 'image', icon: '✏️', symbol: 'RC', category: 'Graphics', brand: 'Recraft', slug: 'recraft-ai/recraft-v3-svg', logo: 'https://logo.clearbit.com/recraft.ai' },
    { name: 'Text to Vector', type: 'image', icon: '📝', symbol: 'T→V', category: 'Graphics', brand: 'Vectorizer', slug: 'vectorizer/text-to-vector' },
    { name: 'Face Align', type: 'image', icon: '👁️', symbol: 'FACE', category: 'Face', brand: 'Face', slug: 'face/align' },
    { name: 'DreamShaper v8', type: 'image', icon: '💭', symbol: 'DS', category: 'Face', brand: 'DreamShaper', slug: 'dreamshaper/v8' },
    { name: 'Text Box', type: 'text', icon: '✍️', symbol: 'TXT', category: 'Helpers', brand: 'AI' },
    { name: 'File Loader', type: 'imageUpload', icon: '📂', symbol: 'FILE', category: 'Helpers', brand: 'AI' },
];
