import { PaletteItem } from '../components/NodeEditor/types';

export const MODELS: PaletteItem[] = [
    { name: 'Stable Diffusion 3.5', type: 'stableDiffusion', icon: '🎨', symbol: 'SD', category: 'Image Gen', brand: 'Stability', logo: 'https://avatars.githubusercontent.com/u/100950301?s=200&v=4' },
    { name: 'GPT Image 1', type: 'stableDiffusion', icon: '🧠', symbol: 'GPT', category: 'Image Gen', brand: 'OpenAI', logo: 'https://logo.clearbit.com/openai.com' },
    { name: 'Imagen 4', type: 'stableDiffusion', icon: '🅶', symbol: 'G', category: 'Image Gen', brand: 'Google', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Imagen 4 Fast', type: 'stableDiffusion', icon: '🅶', symbol: 'G', category: 'Image Gen', brand: 'Google', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Imagen 4 Ultra', type: 'stableDiffusion', icon: '🅶', symbol: 'G', category: 'Image Gen', brand: 'Google', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Imagen 3', type: 'stableDiffusion', icon: '🅶', symbol: 'G', category: 'Image Gen', brand: 'Google', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Imagen 3 Fast', type: 'stableDiffusion', icon: '🅶', symbol: 'G', category: 'Image Gen', brand: 'Google', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Flux Pro 1.1 Ultra', type: 'stableDiffusion', icon: '⚡', symbol: 'FX', category: 'Image Gen', brand: 'Black Forest Labs', logo: 'https://logo.clearbit.com/blackforestlabs.ai' },
    { name: 'Flux Pro 1.1', type: 'stableDiffusion', icon: '⚡', symbol: 'FX', category: 'Image Gen', brand: 'Black Forest Labs', logo: 'https://logo.clearbit.com/blackforestlabs.ai' },
    { name: 'Flux Dev Redux', type: 'stableDiffusion', icon: '⚡', symbol: 'FX', category: 'Image Gen', brand: 'Black Forest Labs', logo: 'https://logo.clearbit.com/blackforestlabs.ai' },
    { name: 'Flux Canny Pro', type: 'stableDiffusion', icon: '⚡', symbol: 'FX', category: 'Image Gen', brand: 'Black Forest Labs', logo: 'https://logo.clearbit.com/blackforestlabs.ai' },
    { name: 'Flux Depth Pro', type: 'stableDiffusion', icon: '⚡', symbol: 'FX', category: 'Image Gen', brand: 'Black Forest Labs', logo: 'https://logo.clearbit.com/blackforestlabs.ai' },
    { name: 'DALL·E 3', type: 'stableDiffusion', icon: '🎨', symbol: 'DAL', category: 'Image Gen', brand: 'OpenAI', logo: 'https://logo.clearbit.com/openai.com' },
    { name: 'Ideogram V3', type: 'stableDiffusion', icon: '📝', symbol: 'ID3', category: 'Image Gen', brand: 'Ideogram', logo: 'https://logo.clearbit.com/ideogram.ai' },
    { name: 'Ideogram V2', type: 'stableDiffusion', icon: '📝', symbol: 'ID2', category: 'Image Gen', brand: 'Ideogram', logo: 'https://logo.clearbit.com/ideogram.ai' },
    { name: 'Minimax Image', type: 'stableDiffusion', icon: '🎵', symbol: 'MX', category: 'Image Gen', brand: 'Minimax' },
    { name: 'Bria', type: 'stableDiffusion', icon: '🎪', symbol: 'BR', category: 'Image Gen', brand: 'Bria', logo: 'https://logo.clearbit.com/bria.ai' },
    { name: 'Kling AI Image', type: 'stableDiffusion', icon: '🤖', symbol: 'KL', category: 'Image Gen', brand: 'Kling', logo: 'https://logo.clearbit.com/klingai.com' },
    { name: 'Gemini 2.5 Flash Image', type: 'stableDiffusion', icon: '🅶', symbol: 'G', category: 'Image Gen', brand: 'Google', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Wan Vace Depth', type: 'stableDiffusion', icon: '🔷', symbol: 'WN', category: 'Image Gen', brand: 'Wan' },
    { name: 'Wan Vace Pose', type: 'stableDiffusion', icon: '🔷', symbol: 'WN', category: 'Image Gen', brand: 'Wan' },
    { name: 'Runway Aleph', type: 'stableDiffusion', icon: '🎬', symbol: 'RW', category: 'Video Gen', brand: 'Runway', logo: 'https://logo.clearbit.com/runwayml.com' },
    { name: 'Runway Act-Two', type: 'stableDiffusion', icon: '🎬', symbol: 'RW', category: 'Video Gen', brand: 'Runway', logo: 'https://logo.clearbit.com/runwayml.com' },
    { name: 'Runway Gen-4', type: 'stableDiffusion', icon: '🎬', symbol: 'RW', category: 'Video Gen', brand: 'Runway', logo: 'https://logo.clearbit.com/runwayml.com' },
    { name: 'Runway Gen-3', type: 'stableDiffusion', icon: '🎬', symbol: 'RW', category: 'Video Gen', brand: 'Runway', logo: 'https://logo.clearbit.com/runwayml.com' },
    { name: 'Luma Reframe', type: 'stableDiffusion', icon: '🎞️', symbol: 'LU', category: 'Video Gen', brand: 'Luma', logo: 'https://logo.clearbit.com/luma.ai' },
    { name: 'Luma Modify', type: 'stableDiffusion', icon: '🎞️', symbol: 'LU', category: 'Video Gen', brand: 'Luma', logo: 'https://logo.clearbit.com/luma.ai' },
    { name: 'Veo 3', type: 'stableDiffusion', icon: '🎬', symbol: 'VEO', category: 'Video Gen', brand: 'Google', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Veo 3 Fast', type: 'stableDiffusion', icon: '🎬', symbol: 'VEO', category: 'Video Gen', brand: 'Google', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Veo 3.1', type: 'stableDiffusion', icon: '🎬', symbol: 'VEO', category: 'Video Gen', brand: 'Google', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Veo 3.1 Fast', type: 'stableDiffusion', icon: '🎬', symbol: 'VEO', category: 'Video Gen', brand: 'Google', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Veo 2', type: 'stableDiffusion', icon: '🎬', symbol: 'VEO', category: 'Video Gen', brand: 'Google', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Veo Text to Video', type: 'stableDiffusion', icon: '📝', symbol: 'VEO', category: 'Video Gen', brand: 'Google', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Veo Image to Video', type: 'stableDiffusion', icon: '🖼️', symbol: 'VEO', category: 'Video Gen', brand: 'Google', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Sora 2', type: 'stableDiffusion', icon: '🎥', symbol: 'SR', category: 'Video Gen', brand: 'OpenAI', logo: 'https://logo.clearbit.com/openai.com' },
    { name: 'Hunyuan Video to Video', type: 'stableDiffusion', icon: '🎥', symbol: 'HY', category: 'Video Gen', brand: 'Hunyuan', logo: 'https://logo.clearbit.com/tencent.com' },
    { name: 'Kling AI Video', type: 'stableDiffusion', icon: '🎥', symbol: 'KLV', category: 'Video Gen', brand: 'Kling', logo: 'https://logo.clearbit.com/klingai.com' },
    { name: 'Wan 2.5', type: 'stableDiffusion', icon: '🔷', symbol: 'WN', category: 'Video Gen', brand: 'Wan' },
    { name: 'Wan 2.2', type: 'stableDiffusion', icon: '🔷', symbol: 'WN', category: 'Video Gen', brand: 'Wan' },
    { name: 'Omnihuman V1.5', type: 'image', icon: '👥', symbol: 'OMN', category: 'Video Gen', brand: 'Omnihuman', logo: 'https://logo.clearbit.com/tencent.com' },
    { name: 'Sync 2 Pro', type: 'image', icon: '🎤', symbol: 'SYN', category: 'Video Gen', brand: 'Sync' },
    { name: 'Pixverse Lipsync', type: 'image', icon: '👄', symbol: 'PIX', category: 'Video Gen', brand: 'Pixverse', logo: 'https://logo.clearbit.com/pixverse.ai' },
    { name: 'Kling AI Avatar', type: 'image', icon: '🤖', symbol: 'KLG', category: 'Video Gen', brand: 'Kling', logo: 'https://logo.clearbit.com/klingai.com' },
    { name: 'Lyria 2', type: 'stableDiffusion', icon: '🎵', symbol: 'LY', category: 'Audio Gen', brand: 'Google', logo: 'https://logo.clearbit.com/google.com' },
    { name: 'Video to Audio', type: 'image', icon: '🎵', symbol: 'V2A', category: 'Audio Gen', brand: 'AI' },
    { name: 'Audio to Video', type: 'image', icon: '🎤', symbol: 'A→V', category: 'Audio Gen', brand: 'AI' },
    { name: 'Rodin', type: 'stableDiffusion', icon: '🎭', symbol: 'ROD', category: '3D', brand: 'Rodin' },
    { name: 'Hunyuan 3D', type: 'stableDiffusion', icon: '🎪', symbol: 'HY3', category: '3D', brand: 'Hunyuan', logo: 'https://logo.clearbit.com/tencent.com' },
    { name: 'Trellis', type: 'stableDiffusion', icon: '📦', symbol: 'TRL', category: '3D', brand: 'Trellis', logo: 'https://logo.clearbit.com/trellis.xyz' },
    { name: 'Meshy', type: 'stableDiffusion', icon: '🧩', symbol: 'MSH', category: '3D', brand: 'Meshy', logo: 'https://logo.clearbit.com/meshy.ai' },
    { name: 'Text Box', type: 'text', icon: '✍️', symbol: 'TXT', category: 'Helpers', brand: 'AI' },
    { name: 'Copilot', type: 'text', icon: '🧠', symbol: 'AI', category: 'Helpers', brand: 'AI' },
    { name: 'Prompt Enhancer', type: 'prompt', icon: '✨', symbol: 'PE', category: 'Helpers', brand: 'AI' },
    { name: 'File Loader', type: 'imageUpload', icon: '📂', symbol: 'FILE', category: 'Helpers', brand: 'AI' },
    { name: 'Sticky Note', type: 'text', icon: '🗒️', symbol: 'NOTE', category: 'Helpers', brand: 'AI' },
    { name: 'Color Palette', type: 'text', icon: '🎨', symbol: 'COL', category: 'Helpers', brand: 'AI' },
  ];

export const TOOLS: PaletteItem[] = [
    { name: 'Remove Background', type: 'image', icon: '🎭', symbol: 'BG-', category: 'Background', brand: 'AI' },
    { name: 'Replace Background', type: 'image', icon: '🌅', symbol: 'BG+', category: 'Background', brand: 'AI' },
    { name: 'Content-Aware Fill', type: 'image', icon: '🎨', symbol: 'FILL', category: 'Background', brand: 'AI' },
    { name: 'Upscale', type: 'upscale', icon: '🔍', symbol: '↑↑', category: 'Edit', brand: 'AI' },
    { name: 'Inpaint', type: 'inpaint', icon: '🖌️', symbol: 'PAINT', category: 'Edit', brand: 'AI' },
    { name: 'Crop', type: 'image', icon: '✂️', symbol: 'CROP', category: 'Edit', brand: 'AI' },
    { name: 'Blur', type: 'image', icon: '💨', symbol: 'BLUR', category: 'Edit', brand: 'AI' },
    { name: 'Invert', type: 'image', icon: '🔄', symbol: 'INV', category: 'Edit', brand: 'AI' },
    { name: 'Relight', type: 'image', icon: '💡', symbol: 'LITE', category: 'Edit', brand: 'AI' },
    { name: 'Video Smoother', type: 'image', icon: '✨', symbol: 'SMOOTH', category: 'Video', brand: 'AI' },
    { name: 'Frame Interpolation', type: 'image', icon: '⚡', symbol: 'FPS', category: 'Video', brand: 'AI' },
    { name: 'Video to Audio', type: 'image', icon: '🎵', symbol: 'V→A', category: 'Video', brand: 'AI' },
    { name: 'Audio to Video', type: 'image', icon: '🎤', symbol: 'A→V', category: 'Video', brand: 'AI' },
    { name: 'Control / IPAdapter SDXL', type: 'image', icon: '⚙️', symbol: 'CTL', category: 'Control', brand: 'SD' },
    { name: 'ID Preservation - Flux', type: 'image', icon: '👤', symbol: 'ID', category: 'Control', brand: 'Black Forest Labs', logo: 'https://logo.clearbit.com/blackforestlabs.ai' },
    { name: 'LoRA Control', type: 'image', icon: '🎛️', symbol: 'LORA', category: 'Control', brand: 'AI' },
    { name: 'Vectorizer', type: 'image', icon: '📐', symbol: 'VEC', category: 'Graphics', brand: 'AI' },
    { name: 'Recraft V3 SVG', type: 'image', icon: '✏️', symbol: 'RC', category: 'Graphics', brand: 'Recraft', logo: 'https://logo.clearbit.com/recraft.ai' },
    { name: 'Text To Vector', type: 'image', icon: '📝', symbol: 'T→V', category: 'Graphics', brand: 'AI' },
    { name: 'Face Align', type: 'image', icon: '👁️', symbol: 'FACE', category: 'Face', brand: 'AI' },
    { name: 'Nano Banana', type: 'image', icon: '🍌', symbol: 'NB', category: 'Face', brand: 'Nano' },
    { name: 'Dreamshaper V8', type: 'image', icon: '💭', symbol: 'DS', category: 'Face', brand: 'Dream' },
    { name: 'Text Box', type: 'text', icon: '✍️', symbol: 'TXT', category: 'Helpers', brand: 'AI' },
    { name: 'File Loader', type: 'imageUpload', icon: '📂', symbol: 'FILE', category: 'Helpers', brand: 'AI' },
  ];

